"""Generator snapshot-style tests focused on stable, repo-grounded content."""

from __future__ import annotations

from pathlib import Path

from repocanon.analyzer import analyze_repo
from repocanon.config import RepoCanonConfig
from repocanon.generators import (
    generate_agents,
    generate_claude,
    generate_copilot,
    generate_cursor,
)
from repocanon.generators.common import MANUAL_BEGIN, MANUAL_END
from repocanon.output.write_files import write_plan


def _content_by_path(plan) -> dict[str, str]:  # type: ignore[no-untyped-def]
    return {f.path: f.content for f in plan.files}


def test_agents_md_grounded(fastapi_repo: Path) -> None:
    model = analyze_repo(fastapi_repo, RepoCanonConfig())
    plan = generate_agents(model)
    files = _content_by_path(plan)
    assert "AGENTS.md" in files
    body = files["AGENTS.md"]
    assert "fastapi-app" in body
    assert "FastAPI" in body
    assert "pytest" in body
    assert MANUAL_BEGIN in body and MANUAL_END in body
    assert "Generated by RepoCanon" in body


def test_claude_md_terse(fastapi_repo: Path) -> None:
    model = analyze_repo(fastapi_repo, RepoCanonConfig())
    plan = generate_claude(model)
    body = _content_by_path(plan)["CLAUDE.md"]
    assert "fastapi-app" in body
    assert "## Must run" in body


def test_copilot_paths(monorepo_repo: Path) -> None:
    model = analyze_repo(monorepo_repo, RepoCanonConfig())
    plan = generate_copilot(model)
    files = _content_by_path(plan)
    assert ".github/copilot-instructions.md" in files
    assert ".github/instructions/packages.instructions.md" in files
    assert "applyTo" in files[".github/instructions/packages.instructions.md"]


def test_cursor_rules_split(nextjs_repo: Path) -> None:
    model = analyze_repo(nextjs_repo, RepoCanonConfig())
    plan = generate_cursor(model)
    paths = {f.path for f in plan.files}
    assert ".cursor/rules/project-overview.mdc" in paths
    assert ".cursor/rules/commands-and-validation.mdc" in paths
    assert ".cursor/rules/code-style-and-conventions.mdc" in paths
    assert ".cursor/rules/architecture-boundaries.mdc" in paths
    overview = next(f for f in plan.files if f.path.endswith("project-overview.mdc"))
    assert overview.content.startswith("---\n")
    assert "alwaysApply: true" in overview.content


def test_safe_overwrite_preserves_manual_block(tmp_path: Path, fastapi_repo: Path) -> None:
    """Manual content between markers should survive regeneration."""
    workdir = tmp_path / "repo"
    _copy_tree(fastapi_repo, workdir)

    model = analyze_repo(workdir, RepoCanonConfig())
    write_plan(generate_agents(model), workdir, force=False, safe_overwrite=True)

    agents = workdir / "AGENTS.md"
    text = agents.read_text("utf-8")
    seam = f"{MANUAL_BEGIN}\nKEEP_ME\n{MANUAL_END}"
    text = text.replace(
        text[text.index(MANUAL_BEGIN) : text.index(MANUAL_END) + len(MANUAL_END)],
        seam,
    )
    agents.write_text(text, encoding="utf-8")

    write_plan(generate_agents(model), workdir, force=False, safe_overwrite=True)
    after = agents.read_text("utf-8")
    assert "KEEP_ME" in after


def _copy_tree(src: Path, dst: Path) -> None:
    import shutil

    shutil.copytree(src, dst)
