"""Shared building blocks used by every target-specific generator.

Each generator turns a ``ProjectModel`` into Markdown. To keep outputs
readable and grounded, every section is generated from concrete facts and is
omitted entirely when no facts are available — we never pad with filler.
"""

from __future__ import annotations

from collections.abc import Iterable

from repocanon.models.findings import Confidence
from repocanon.models.project import (
    CommandSet,
    Convention,
    DirectoryRole,
    Framework,
    Language,
    PackageManager,
    ProjectModel,
)
from repocanon.utils.text import bullet_list as bullet_list
from repocanon.utils.text import section as section
from repocanon.utils.text import truncate as truncate

HEADER_NOTICE = (
    "<!-- Generated by RepoCanon. Safe to edit by hand; regenerate with "
    "`repocanon generate {target} .` to refresh inferred sections. -->"
)

MANUAL_BEGIN = "<!-- repocanon:manual:begin -->"
MANUAL_END = "<!-- repocanon:manual:end -->"


def manual_block(existing: str = "") -> str:
    """Render a preserved manual-edits block.

    When ``existing`` already contains a RepoCanon-managed file, only the
    prior manual section is reused so we don't accidentally embed the entire
    previous file inside the new one.
    """
    prior = split_manual_block(existing) if existing else ""
    inner = prior.strip()
    body = f"\n{inner}\n" if inner else "\n_Add notes that should survive regeneration here._\n"
    return f"{MANUAL_BEGIN}{body}{MANUAL_END}"


def header(target: str) -> str:
    return HEADER_NOTICE.format(target=target)


def overview_paragraph(model: ProjectModel) -> str:
    primary = model.primary_language() or "an unidentified primary language"
    fw_summary = ", ".join(fw.name for fw in model.frameworks[:5]) or "no major frameworks detected"
    topo = model.topology.value.replace("_", " ")
    return (
        f"`{model.repo_name}` is a {topo} repository written primarily in {primary}. "
        f"Detected frameworks/tools: {fw_summary}."
    )


def languages_block(languages: Iterable[Language]) -> str:
    items = [f"{lang.name} ({lang.file_count} files)" for lang in languages if lang.file_count]
    return bullet_list(items)


def frameworks_block(frameworks: Iterable[Framework]) -> str:
    items = [f"{fw.name} — {fw.category}" for fw in frameworks]
    return bullet_list(items)


def package_managers_block(pms: Iterable[PackageManager]) -> str:
    return bullet_list([f"{pm.name} (`{pm.manifest}`)" for pm in pms])


def commands_block(commands: CommandSet, *, terse: bool = False) -> str:
    """Render commands as a Markdown sublist, grouped by purpose."""
    groups = (
        ("Install", commands.install),
        ("Dev", commands.dev),
        ("Build", commands.build),
        ("Test", commands.test),
        ("Lint", commands.lint),
        ("Format", commands.format),
        ("Typecheck", commands.typecheck),
    )
    rendered: list[str] = []
    for label, items in groups:
        if not items:
            continue
        if terse:
            rendered.append(f"- **{label}**: `{items[0]}`")
        else:
            joined = "\n".join(f"  - `{cmd}`" for cmd in items)
            rendered.append(f"- **{label}**\n{joined}")
    if commands.extras and not terse:
        for k, items in commands.extras.items():
            if not items:
                continue
            joined = "\n".join(f"  - `{cmd}`" for cmd in items[:8])
            rendered.append(f"- **Other {k}**\n{joined}")
    return "\n".join(rendered)


def directories_block(dirs: Iterable[DirectoryRole]) -> str:
    return bullet_list([f"`{d.path}/` — {d.role}" for d in dirs])


def conventions_block(conventions: Iterable[Convention]) -> str:
    return bullet_list([f"**{c.name}**: {c.value}" for c in conventions])


def boundaries_block(model: ProjectModel) -> str:
    items = [f"**{b.name}** — {b.description}" for b in model.architecture_boundaries]
    return bullet_list(items)


def anti_patterns_block(model: ProjectModel) -> str:
    return bullet_list(model.anti_patterns)


def uncertainty_block(model: ProjectModel) -> str:
    notes = list(model.uncertainty_notes)
    low_conf = [
        f"Low-confidence inference: {f.subject} — {truncate(f.rationale, 140)}"
        for f in model.findings
        if f.confidence is Confidence.low
    ]
    return bullet_list(notes + low_conf)


def standard_sections(model: ProjectModel, *, terse: bool = False) -> list[str]:
    """The set of sections shared by AGENTS.md and CLAUDE.md."""
    return [
        section("Project overview", overview_paragraph(model), level=2),
        section("Languages", languages_block(model.languages), level=2),
        section("Frameworks and tools", frameworks_block(model.frameworks), level=2),
        section("Package managers", package_managers_block(model.package_managers), level=2),
        section("Commands", commands_block(model.commands, terse=terse), level=2),
        section("Repository layout", directories_block(model.key_directories), level=2),
        section(
            "Conventions",
            conventions_block([*model.conventions, *model.naming_conventions]),
            level=2,
        ),
        section("Architecture boundaries", boundaries_block(model), level=2),
        section("Avoid", anti_patterns_block(model), level=2),
        section("Uncertainty", uncertainty_block(model), level=2),
    ]


def split_manual_block(existing: str) -> str:
    """Extract the contents between manual markers in an existing file."""
    if MANUAL_BEGIN not in existing or MANUAL_END not in existing:
        return ""
    start = existing.index(MANUAL_BEGIN) + len(MANUAL_BEGIN)
    end = existing.index(MANUAL_END)
    return existing[start:end].strip()
