"""Write generated files to disk, optionally preserving manual edits.

Manual-block preservation is owned entirely by this module: generators emit
empty manual markers (``MANUAL_BEGIN`` / ``MANUAL_END``) and the writer is
responsible for reading the previous on-disk file and re-injecting whatever
the user wrote between those markers. Generators no longer take an
``existing`` parameter.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from repocanon.models.outputs import GenerationPlan

MANUAL_BEGIN = "<!-- repocanon:manual:begin -->"
MANUAL_END = "<!-- repocanon:manual:end -->"


@dataclass
class WriteResult:
    path: Path
    action: str  # "created" | "updated" | "skipped"
    bytes_written: int


def split_manual_block(existing: str) -> str:
    """Extract the contents between manual markers in an existing file."""
    if MANUAL_BEGIN not in existing or MANUAL_END not in existing:
        return ""
    start = existing.index(MANUAL_BEGIN) + len(MANUAL_BEGIN)
    end = existing.index(MANUAL_END)
    return existing[start:end].strip()


def merge_manual_block(new_content: str, existing_content: str) -> str:
    """Replace the manual block in ``new_content`` with the user's prior content."""
    if MANUAL_BEGIN not in new_content or MANUAL_END not in new_content:
        return new_content
    prior = split_manual_block(existing_content)
    if not prior:
        return new_content
    start = new_content.index(MANUAL_BEGIN) + len(MANUAL_BEGIN)
    end = new_content.index(MANUAL_END)
    return new_content[:start] + f"\n{prior}\n" + new_content[end:]


def write_plan(
    plan: GenerationPlan,
    repo_path: Path,
    *,
    output_dir: Path | None = None,
    dry_run: bool = False,
    force: bool = False,
    safe_overwrite: bool = True,
) -> list[WriteResult]:
    """Materialize a :class:`GenerationPlan` to disk.

    - ``dry_run``: log only, do not write.
    - ``force``: overwrite without trying to preserve manual blocks.
    - ``safe_overwrite``: when a destination already contains a manual block,
      keep its contents. Has no effect when ``force`` is True.
    - ``output_dir``: redirect writes to this directory instead of
      ``repo_path``. Path-traversal protection refuses to write outside the
      requested base.
    """
    base = (output_dir or repo_path).resolve()
    results: list[WriteResult] = []

    for f in plan.files:
        target_path = (base / f.path).resolve()
        # Protect against generators (or hand-edited paths) that would escape
        # the requested output base via .. or absolute paths.
        try:
            target_path.relative_to(base)
        except ValueError as exc:
            raise PermissionError(
                f"Refusing to write outside output base: {target_path}"
            ) from exc

        existing = target_path.read_text("utf-8") if target_path.exists() else ""
        action: str
        content = f.content
        if existing:
            if force:
                action = "updated"
            elif safe_overwrite:
                content = merge_manual_block(f.content, existing)
                action = "updated" if content != existing else "skipped"
            else:
                action = "updated"
        else:
            action = "created"

        if not dry_run and action != "skipped":
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")

        results.append(
            WriteResult(
                path=target_path,
                action=action,
                bytes_written=len(content.encode("utf-8")) if action != "skipped" else 0,
            )
        )
    return results


def remove_generated(
    plan_files: list[str],
    repo_path: Path,
    *,
    dry_run: bool = False,
) -> list[Path]:
    """Delete generated files. Used by ``repocanon clean``.

    Only files that exist *and* contain RepoCanon's header marker are removed,
    so user-authored files at the same path are never touched.
    """
    removed: list[Path] = []
    for rel in plan_files:
        path = (repo_path / rel).resolve()
        if not path.exists():
            continue
        try:
            text = path.read_text("utf-8")
        except OSError:
            continue
        if "Generated by RepoCanon" not in text:
            continue
        if not dry_run:
            try:
                path.unlink()
            except OSError:
                continue
        removed.append(path)
    return removed
