"""Write generated files to disk while preserving the user's hand-written content.

Three on-disk states are recognized for any target path:

1. **No file** — write our generated content as-is.
2. **Our file** (contains ``HEADER_MARKER``) — regenerate, preserving the
   inner ``MANUAL_BEGIN``/``MANUAL_END`` block.
3. **User's file** (no ``HEADER_MARKER``) — never overwrite. Either:
   - already contains a ``SECTION_BEGIN``/``SECTION_END`` block we appended
     on a previous run → replace just that block.
   - has no RepoCanon section yet → append our generated content at the
     bottom, wrapped in section markers, separated from user content by an
     `<hr>`.

``--force`` bypasses all of this and overwrites blindly.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from repocanon.models.outputs import GenerationPlan

MANUAL_BEGIN = "<!-- repocanon:manual:begin -->"
MANUAL_END = "<!-- repocanon:manual:end -->"

SECTION_BEGIN = "<!-- repocanon:section:begin -->"
SECTION_END = "<!-- repocanon:section:end -->"
SECTION_SEPARATOR = "\n\n---\n\n"

HEADER_MARKER = "Generated by RepoCanon"


@dataclass
class WriteResult:
    path: Path
    action: str  # "created" | "updated" | "appended" | "skipped"
    bytes_written: int


def split_manual_block(existing: str) -> str:
    """Extract the contents between manual markers in an existing file."""
    if MANUAL_BEGIN not in existing or MANUAL_END not in existing:
        return ""
    start = existing.index(MANUAL_BEGIN) + len(MANUAL_BEGIN)
    end = existing.index(MANUAL_END)
    return existing[start:end].strip()


def merge_manual_block(new_content: str, existing_content: str) -> str:
    """Replace the manual block in ``new_content`` with the user's prior content."""
    if MANUAL_BEGIN not in new_content or MANUAL_END not in new_content:
        return new_content
    prior = split_manual_block(existing_content)
    if not prior:
        return new_content
    start = new_content.index(MANUAL_BEGIN) + len(MANUAL_BEGIN)
    end = new_content.index(MANUAL_END)
    return new_content[:start] + f"\n{prior}\n" + new_content[end:]


def _wrap_section(generated: str) -> str:
    """Wrap our generated content in section markers for embedding in user files."""
    return f"{SECTION_BEGIN}\n{generated.strip()}\n{SECTION_END}"


def _has_section(text: str) -> bool:
    if SECTION_BEGIN not in text or SECTION_END not in text:
        return False
    return text.index(SECTION_BEGIN) < text.index(SECTION_END)


def _replace_section(existing: str, generated: str) -> str:
    """Replace the existing RepoCanon section with a freshly-rendered one.

    Manual-block content inside the prior section is preserved.
    """
    begin = existing.index(SECTION_BEGIN)
    end = existing.index(SECTION_END) + len(SECTION_END)
    prior_section = existing[begin:end]
    refreshed_inner = merge_manual_block(generated, prior_section)
    return existing[:begin] + _wrap_section(refreshed_inner) + existing[end:]


def _append_section(existing: str, generated: str) -> str:
    """Append a new RepoCanon section to the bottom of the user's file."""
    body = existing.rstrip()
    return f"{body}{SECTION_SEPARATOR}{_wrap_section(generated)}\n"


def write_plan(
    plan: GenerationPlan,
    repo_path: Path,
    *,
    output_dir: Path | None = None,
    dry_run: bool = False,
    force: bool = False,
    safe_overwrite: bool = True,
) -> list[WriteResult]:
    """Materialize a :class:`GenerationPlan` to disk.

    - ``dry_run``: log only, do not write.
    - ``force``: overwrite without preserving manual blocks or user content.
    - ``safe_overwrite``: when False (and ``force`` False), behaves like
      ``force`` for our own files but still appends to user files. Mostly a
      legacy knob; prefer ``force`` for blind overwrites.
    - ``output_dir``: redirect writes to this directory instead of
      ``repo_path``. Path-traversal protection refuses to write outside the
      requested base.
    """
    base = (output_dir or repo_path).resolve()
    results: list[WriteResult] = []

    for f in plan.files:
        target_path = (base / f.path).resolve()
        try:
            target_path.relative_to(base)
        except ValueError as exc:
            raise PermissionError(
                f"Refusing to write outside output base: {target_path}"
            ) from exc

        existing = target_path.read_text("utf-8") if target_path.exists() else ""
        content, action = _resolve_write(
            generated=f.content,
            existing=existing,
            force=force,
            safe_overwrite=safe_overwrite,
        )

        if not dry_run and action != "skipped":
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")

        results.append(
            WriteResult(
                path=target_path,
                action=action,
                bytes_written=len(content.encode("utf-8")) if action != "skipped" else 0,
            )
        )
    return results


def _resolve_write(
    *,
    generated: str,
    existing: str,
    force: bool,
    safe_overwrite: bool,
) -> tuple[str, str]:
    """Decide what to write for one file. Returns (final_content, action)."""
    if not existing:
        return generated, "created"

    if force:
        return generated, "updated"

    # Order matters: a user file we appended into ALSO contains HEADER_MARKER
    # (inside the embedded section), so check section markers first.
    if _has_section(existing):
        refreshed = _replace_section(existing, generated)
        if refreshed == existing:
            return existing, "skipped"
        return refreshed, "updated"

    if HEADER_MARKER in existing:
        # File was created by RepoCanon — full regen with manual-block preserved.
        if not safe_overwrite:
            return generated, "updated"
        merged = merge_manual_block(generated, existing)
        if merged == existing:
            return existing, "skipped"
        return merged, "updated"

    return _append_section(existing, generated), "appended"


def remove_generated(
    plan_files: list[str],
    repo_path: Path,
    *,
    dry_run: bool = False,
) -> list[Path]:
    """Delete generated files. Used by ``repocanon clean``.

    Only files where RepoCanon owns the *entire* file (i.e. they contain
    ``HEADER_MARKER`` and were not appended into a user-authored file) are
    removed. Files where we appended a section into the user's content are
    left alone — use ``--force`` semantics in a future release if needed.
    """
    removed: list[Path] = []
    for rel in plan_files:
        path = (repo_path / rel).resolve()
        if not path.exists():
            continue
        try:
            text = path.read_text("utf-8")
        except OSError:
            continue
        if HEADER_MARKER not in text:
            continue
        # If we appended a section into a user file, the very first non-empty
        # line will not be ours. Refuse to delete in that case.
        if _has_section(text) and not text.lstrip().startswith("<!--"):
            continue
        if not dry_run:
            try:
                path.unlink()
            except OSError:
                continue
        removed.append(path)
    return removed
